// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using backendVeterinaria.Data;

#nullable disable

namespace backendVeterinaria.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240422042314_CreacionInicial")]
    partial class CreacionInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("backendVeterinaria.Models.Empleados", b =>
                {
                    b.Property<int>("empleadosId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("empleadosId"));

                    b.Property<string>("correo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("curp")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("estatusId")
                        .HasColumnType("integer");

                    b.Property<string>("fecha_baja")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("fecha_ingreso")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("personasId")
                        .HasColumnType("integer");

                    b.Property<int>("rolesId")
                        .HasColumnType("integer");

                    b.Property<string>("sexo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("empleadosId");

                    b.HasIndex("estatusId");

                    b.HasIndex("personasId");

                    b.HasIndex("rolesId");

                    b.ToTable("Empleados");
                });

            modelBuilder.Entity("backendVeterinaria.Models.Estatus", b =>
                {
                    b.Property<int>("estatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("estatusId"));

                    b.Property<string>("nombre_estatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("estatusId");

                    b.ToTable("Estatus");

                    b.HasData(
                        new
                        {
                            estatusId = 1,
                            nombre_estatus = "Activo"
                        },
                        new
                        {
                            estatusId = 2,
                            nombre_estatus = "Inactivo"
                        });
                });

            modelBuilder.Entity("backendVeterinaria.Models.Personas", b =>
                {
                    b.Property<int>("personasId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("personasId"));

                    b.Property<string>("apellido_materno")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("apellido_paterno")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("telefono")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("tipo_persona")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("personasId");

                    b.ToTable("Personas");
                });

            modelBuilder.Entity("backendVeterinaria.Models.Roles", b =>
                {
                    b.Property<int?>("rolesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int?>("rolesId"));

                    b.Property<string>("nombre_rol")
                        .HasColumnType("text");

                    b.HasKey("rolesId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            rolesId = 1,
                            nombre_rol = "Comercial"
                        },
                        new
                        {
                            rolesId = 2,
                            nombre_rol = "General"
                        });
                });

            modelBuilder.Entity("backendVeterinaria.Models.Empleados", b =>
                {
                    b.HasOne("backendVeterinaria.Models.Estatus", "estatus")
                        .WithMany("empleados")
                        .HasForeignKey("estatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backendVeterinaria.Models.Personas", "personas")
                        .WithMany("empleados")
                        .HasForeignKey("personasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backendVeterinaria.Models.Roles", "roles")
                        .WithMany("empleados")
                        .HasForeignKey("rolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("estatus");

                    b.Navigation("personas");

                    b.Navigation("roles");
                });

            modelBuilder.Entity("backendVeterinaria.Models.Estatus", b =>
                {
                    b.Navigation("empleados");
                });

            modelBuilder.Entity("backendVeterinaria.Models.Personas", b =>
                {
                    b.Navigation("empleados");
                });

            modelBuilder.Entity("backendVeterinaria.Models.Roles", b =>
                {
                    b.Navigation("empleados");
                });
#pragma warning restore 612, 618
        }
    }
}
